CFLAGS  := -std=c99 -Wall -Werror -O2 -D_REENTRANT
LIBS    := -lpthread -lm -lcrypto -lssl

TARGET  := $(shell uname -s | tr '[A-Z]' '[a-z]' 2>/dev/null || echo unknown)

# Include platform-specific settings generated by ./configure.
# Run ./configure once before the first build; re-run after OS/toolchain changes.
-include config.mk

SRC  := wrk.c net.c ssl.c aprintf.c stats.c script.c units.c \
		ae.c zmalloc.c http_parser.c tinymt64.c hdr_histogram.c
BIN  := wrkx

ODIR := obj
OBJ  := $(patsubst %.c,$(ODIR)/%.o,$(SRC)) $(ODIR)/bytecode.o

LDIR     = deps/luajit/src
LIBS    := -lluajit $(LIBS)
CFLAGS  += -I$(LDIR)
LDFLAGS += -L$(LDIR)

all: $(BIN)

clean:
	@rm -rf obj/cov
	$(RM) $(BIN) obj/*
	@$(MAKE) -C deps/luajit clean

$(BIN): $(OBJ)
	@echo LINK $(BIN)
	@$(CC) $(LDFLAGS) -o $@ $^ $(LIBS)

$(OBJ): config.h Makefile $(LDIR)/libluajit.a | $(ODIR)

$(ODIR):
	@mkdir -p $@

$(ODIR)/bytecode.o: src/wrk.lua
	@echo LUAJIT $<
	@$(SHELL) -c 'cd $(LDIR) && ./luajit -b $(CURDIR)/$< $(CURDIR)/$@'

$(ODIR)/%.o : %.c
	@echo CC $<
	@$(CC) $(CFLAGS) -c -o $@ $<

$(LDIR)/libluajit.a:
	@echo Building LuaJIT...
	@$(MAKE) -C $(LDIR) BUILDMODE=static

test: test-unit test-e2e
UNITY_SRC := deps/unity/unity.c
UNITY_INC := -Ideps/unity
TEST_UNIT_SRC := tests/unit/runner.c
TEST_UNIT_BIN := obj/test_unit

TEST_STATS_SRC := tests/unit/test_stats.c
TEST_STATS_BIN := obj/test_stats
STATS_DEPS     := src/stats.c src/zmalloc.c src/tinymt64.c src/hdr_histogram.c

TEST_UNITS_SRC := tests/unit/test_units.c
TEST_UNITS_BIN := obj/test_units
UNITS_DEPS     := src/units.c src/aprintf.c src/zmalloc.c

TEST_HDR_SRC := tests/unit/test_hdr.c
TEST_HDR_BIN := obj/test_hdr
HDR_DEPS     := src/hdr_histogram.c

test-unit: $(TEST_UNIT_BIN) $(TEST_STATS_BIN) $(TEST_UNITS_BIN) $(TEST_HDR_BIN)
	@./$(TEST_UNIT_BIN)
	@./$(TEST_STATS_BIN)
	@./$(TEST_UNITS_BIN)
	@./$(TEST_HDR_BIN)

$(TEST_UNIT_BIN): $(TEST_UNIT_SRC) $(UNITY_SRC) | $(ODIR)
	@$(CC) $(CFLAGS) $(UNITY_INC) -o $@ $^

$(TEST_STATS_BIN): $(TEST_STATS_SRC) $(UNITY_SRC) $(STATS_DEPS) | $(ODIR)
	@$(CC) $(CFLAGS) $(UNITY_INC) -Isrc -DUNITY_INCLUDE_DOUBLE -o $@ $^ -lm -lpthread

$(TEST_UNITS_BIN): $(TEST_UNITS_SRC) $(UNITY_SRC) $(UNITS_DEPS) | $(ODIR)
	@$(CC) $(CFLAGS) $(UNITY_INC) -Isrc -include tests/unit/platform_compat.h -o $@ $^ -lpthread

$(TEST_HDR_BIN): $(TEST_HDR_SRC) $(UNITY_SRC) $(HDR_DEPS) | $(ODIR)
	@$(CC) $(CFLAGS) $(UNITY_INC) -Isrc -o $@ $^ -lm
test-e2e:
	@bash tests/e2e/smoke.sh
	@bash tests/e2e/latency.sh
	@bash tests/e2e/reconnect.sh
	@bash tests/e2e/errors.sh
# ---------------------------------------------------------------------------
# ASAN + UBSan unit tests
# NOTE: the full wrkx binary is NOT instrumented here — LuaJIT's custom
# mmap-based allocator conflicts with ASAN's shadow memory on both macOS
# and Linux, causing false positives. Unit test binaries have no LuaJIT
# dependency and can be fully instrumented. The smoke E2E runs the
# release binary so the full request path is still exercised.
#
# Linux note: if using GCC, ensure libasan is installed (gcc-sanitizers
# or libasan package). With Clang, compiler-rt provides the runtime.
# ---------------------------------------------------------------------------
ASANFLAGS := -fsanitize=address,undefined -fno-omit-frame-pointer -O1

test-asan: | $(ODIR)
	@echo "Building ASAN/UBSan unit test binaries..."
	@$(CC) $(CFLAGS) $(ASANFLAGS) $(UNITY_INC) -Isrc -DUNITY_INCLUDE_DOUBLE \
		-o obj/asan_stats \
		$(TEST_STATS_SRC) $(UNITY_SRC) $(STATS_DEPS) -lm -lpthread
	@$(CC) $(CFLAGS) $(ASANFLAGS) $(UNITY_INC) -Isrc \
		-include tests/unit/platform_compat.h \
		-o obj/asan_units \
		$(TEST_UNITS_SRC) $(UNITY_SRC) $(UNITS_DEPS) -lpthread
	@$(CC) $(CFLAGS) $(ASANFLAGS) $(UNITY_INC) -Isrc \
		-o obj/asan_hdr \
		$(TEST_HDR_SRC) $(UNITY_SRC) $(HDR_DEPS) -lm
	@echo "Running ASAN/UBSan unit tests..."
	@./obj/asan_stats
	@./obj/asan_units
	@./obj/asan_hdr
	@echo "Running smoke E2E against release binary..."
	@bash tests/e2e/smoke.sh

# ---------------------------------------------------------------------------
# Coverage via gcov
# ---------------------------------------------------------------------------
COVFLAGS := --coverage -O0 -fno-inline
COV_DIR  := obj/cov

coverage: | $(ODIR)
	@rm -rf $(COV_DIR) && mkdir -p $(COV_DIR)
	@echo "Building test_stats with coverage..."
	@$(CC) $(CFLAGS) $(COVFLAGS) $(UNITY_INC) -Isrc -DUNITY_INCLUDE_DOUBLE \
		-o $(COV_DIR)/test_stats \
		$(TEST_STATS_SRC) $(UNITY_SRC) $(STATS_DEPS) -lm -lpthread
	@echo "Building test_units with coverage..."
	@$(CC) $(CFLAGS) $(COVFLAGS) $(UNITY_INC) -Isrc \
		-include tests/unit/platform_compat.h \
		-o $(COV_DIR)/test_units \
		$(TEST_UNITS_SRC) $(UNITY_SRC) $(UNITS_DEPS) -lpthread
	@echo "Running covered test binaries..."
	@cd $(COV_DIR) && ./test_stats  > /dev/null
	@cd $(COV_DIR) && ./test_units  > /dev/null
	@echo "Generating gcov reports..."
	@gcov -o $(COV_DIR) $(COV_DIR)/test_stats-stats     2>&1 | grep -E "^File|^Lines"
	@gcov -o $(COV_DIR) $(COV_DIR)/test_units-units     2>&1 | grep -E "^File|^Lines"
	@echo "Checking coverage thresholds (>= 80%)..."
	@bash -c '\
		for pair in "$(COV_DIR)/test_stats-stats:stats.c" "$(COV_DIR)/test_units-units:units.c"; do \
			gcno=$${pair%%:*}; label=$${pair##*:}; \
			pct=$$(gcov -o $(COV_DIR) $$gcno 2>&1 | grep "Lines executed" | head -1 | grep -oE "[0-9]+\.[0-9]+"); \
			int_pct=$$(echo "$$pct" | cut -d. -f1); \
			if [ "$$int_pct" -lt 80 ]; then \
				echo "FAIL: $$label coverage $${pct}% < 80%"; exit 1; \
			else \
				echo "PASS: $$label coverage $${pct}%"; \
			fi; \
		done'

.PHONY: all clean test test-unit test-e2e test-asan coverage
.SUFFIXES:
.SUFFIXES: .c .o .lua

vpath %.c   src
vpath %.h   src
vpath %.lua scripts
