EXT_SRCS     += extensions/redis/redis.c \
                extensions/redis/resp.c \
                extensions/redis/redis_lua_helpers.c \
                extensions/redis/init.c
EXT_INIT_FNS += wrkx_extension_init_redis
EXT_CFLAGS   += -Iextensions/redis
