/*
 * src/main.c — wrkx entry point (ADR 0001 Phase 1, P1-5).
 *
 * Wires the three layers together:
 *   1. cli.c  — parse argv → orchestrator_cfg + url + script + headers
 *   2. Protocol detection — built-in HTTP/HTTPS, or extension-registered schemas
 *   3. <proto>_configure() — resolve target + supply connect info (ADR 0002 §2)
 *   4. api->configure()   — supply URL/headers to Lua engine  (ADR 0002 §3)
 *   5. api->init()        — run wrk.init(); set up default request closure
 *   6. orchestrator_create/run/collect/destroy
 *
 * This is the only file that legitimately includes headers from all three
 * layers (it is the wiring, not a layer).
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <netdb.h>
#include <signal.h>
#include <unistd.h>
#include <sys/socket.h>

#include <openssl/ssl.h>
#include <openssl/err.h>

#include "config.h"
#include "cli.h"
#include "orchestrator.h"
#include "proto/http1.h"
#include "scripting/lua/engine.h"
#include "scripting/script_api.h"
#include "scripting/helper_tag.h"
#include "units.h"
#include "http_parser.h"
#include "wrkx_extension.h"

/* Generated by scripts/gen_register_extensions.sh into obj/register_extensions.c.
 * Calls wrkx_extension_init_<name>(api) for each extension active at build time. */
extern void wrkx_register_all_extensions(const wrkx_extension_api *api);

/* ssl_init() from ssl.c — declared directly to avoid ssl.h → net.h → wrk.h */
extern SSL_CTX *ssl_init(void);

/* -------------------------------------------------------------------------
 * Extension registry
 *
 * Extensions register protocols, helper namespaces, and URL schemas at
 * startup via the wrkx_extension_api callbacks below. The host applies
 * helpers to each engine after creation and dispatches schema-based
 * configuration to the registered configure callback.
 * ---------------------------------------------------------------------- */

#define MAX_EXT_SCHEMAS     8
#define MAX_EXT_HELPER_SETS 8

typedef struct {
    const char        *schema;
    const char        *schema_tls;
    const char        *default_port;
    wrkx_configure_fn  configure;
    const protocol    *proto;
} schema_reg;

typedef struct {
    const char          *ns;
    const script_helper *helpers;
    size_t               count;
} helper_set;

static const protocol *g_registered_proto = NULL;
static schema_reg      g_schemas[MAX_EXT_SCHEMAS];
static int             g_schema_count = 0;
static helper_set      g_helper_sets[MAX_EXT_HELPER_SETS];
static int             g_helper_set_count = 0;

static void ext_reg_protocol(const protocol *p) {
    g_registered_proto = p;
}

static void ext_reg_helpers(const char *ns, const script_helper *h, size_t n) {
    if (g_helper_set_count < MAX_EXT_HELPER_SETS)
        g_helper_sets[g_helper_set_count++] = (helper_set){ns, h, n};
}

static void ext_reg_schema(const char *schema, const char *schema_tls,
                           const char *default_port, wrkx_configure_fn configure) {
    if (g_schema_count < MAX_EXT_SCHEMAS)
        g_schemas[g_schema_count++] =
            (schema_reg){schema, schema_tls, default_port, configure,
                         g_registered_proto};
}

static const wrkx_extension_api g_ext_api = {
    WRKX_EXTENSION_API_VERSION,
    ext_reg_protocol,
    ext_reg_helpers,
    ext_reg_schema,
};

/* -------------------------------------------------------------------------
 * Protocol detection
 *
 * HTTP/HTTPS are built-in. All other schemas are resolved through the
 * extension schema registry populated by wrkx_register_all_extensions().
 * ---------------------------------------------------------------------- */

typedef struct {
    bool        found;
    bool        use_ext;    /* false = built-in HTTP/1.1 */
    bool        need_tls;
    const char *default_port;
    int         schema_idx; /* index into g_schemas if use_ext */
} proto_detect;

static proto_detect detect_protocol(const char *schema) {
    proto_detect d = { false, false, false, "80", -1 };
    if (!schema) { d.found = true; return d; }

    if (strcmp(schema, "http") == 0) {
        d.found = true; d.need_tls = false; d.default_port = "80";
        return d;
    }
    if (strcmp(schema, "https") == 0) {
        d.found = true; d.need_tls = true; d.default_port = "443";
        return d;
    }

    for (int i = 0; i < g_schema_count; i++) {
        if (strcmp(schema, g_schemas[i].schema) == 0) {
            d.found = true; d.use_ext = true;
            d.need_tls = false;
            d.default_port = g_schemas[i].default_port;
            d.schema_idx = i;
            return d;
        }
        if (g_schemas[i].schema_tls &&
            strcmp(schema, g_schemas[i].schema_tls) == 0) {
            d.found = true; d.use_ext = true;
            d.need_tls = true;
            d.default_port = g_schemas[i].default_port;
            d.schema_idx = i;
            return d;
        }
    }
    return d;
}

/* -------------------------------------------------------------------------
 * URL decomposition helper (local to wiring)
 * ---------------------------------------------------------------------- */

static char *url_part(const char *url, const struct http_parser_url *p,
                      enum http_parser_url_fields f) {
    if (!(p->field_set & (1 << f))) return NULL;
    uint16_t off = p->field_data[f].off;
    uint16_t len = p->field_data[f].len;
    char *s = calloc(len + 1, 1);
    if (s) memcpy(s, url + off, len);
    return s;
}

/*
 * Pick the first resolved address that actually accepts a connection.
 */
static struct addrinfo *pick_reachable(struct addrinfo *list) {
    for (struct addrinfo *a = list; a != NULL; a = a->ai_next) {
        int fd = socket(a->ai_family, a->ai_socktype, a->ai_protocol);
        if (fd < 0) continue;
        int ok = (connect(fd, a->ai_addr, a->ai_addrlen) == 0);
        close(fd);
        if (ok) return a;
    }
    return list;
}

/* -------------------------------------------------------------------------
 * main
 * ---------------------------------------------------------------------- */

int main(int argc, char **argv) {
    /* ------------------------------------------------------------------
     * 1.  Parse CLI arguments.
     * ---------------------------------------------------------------- */
    char *header_buf[CLI_MAX_HEADERS];
    cli_args args;
    args.headers = header_buf;

    if (cli_parse_args(argc, argv, &args) != 0) {
        cli_usage(argv[0]);
        return 1;
    }

    /* ------------------------------------------------------------------
     * 2.  Decompose URL.
     * ---------------------------------------------------------------- */
    struct http_parser_url parts;
    memset(&parts, 0, sizeof(parts));
    http_parser_parse_url(args.url, strlen(args.url), 0, &parts);

    char *schema = url_part(args.url, &parts, UF_SCHEMA);
    char *host   = url_part(args.url, &parts, UF_HOST);
    char *port   = url_part(args.url, &parts, UF_PORT);

    /* ------------------------------------------------------------------
     * 3.  Initialise active extensions (they register schemas here).
     * ---------------------------------------------------------------- */
    wrkx_register_all_extensions(&g_ext_api);

    /* ------------------------------------------------------------------
     * 4.  Detect protocol — must happen after extensions register schemas.
     * ---------------------------------------------------------------- */
    proto_detect pd = detect_protocol(schema);

    if (!pd.found) {
        fprintf(stderr, "wrkx: no extension provides '%s://' — "
                "rebuild with EXTENSIONS=<name>\n",
                schema ? schema : "(null)");
        return 1;
    }

    const char *service = port ? port : pd.default_port;

    /* ------------------------------------------------------------------
     * 5.  TLS setup — driven by schema detection, not by schema string.
     * ---------------------------------------------------------------- */
    SSL_CTX *ssl_ctx = NULL;
    if (pd.need_tls) {
        ssl_ctx = ssl_init();
        if (ssl_ctx == NULL) {
            fprintf(stderr, "unable to initialise SSL\n");
            ERR_print_errors_fp(stderr);
            return 1;
        }
    }

    /* ------------------------------------------------------------------
     * 6.  Resolve host:service → addrinfo.
     * ---------------------------------------------------------------- */
    struct addrinfo hints, *addr = NULL;
    memset(&hints, 0, sizeof(hints));
    hints.ai_family   = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;

    int rc = getaddrinfo(host, service, &hints, &addr);
    if (rc != 0) {
        fprintf(stderr, "unable to resolve %s:%s — %s\n",
                host ? host : "(null)", service ? service : "(null)",
                gai_strerror(rc));
        return 1;
    }

    /* ------------------------------------------------------------------
     * 7.  Configure the Protocol Engine (ADR 0002 Decision 2).
     * ---------------------------------------------------------------- */
    signal(SIGPIPE, SIG_IGN);

    if (pd.use_ext) {
        /* Extension protocol: extract URL components and invoke configure. */
        char *password = url_part(args.url, &parts, UF_USERINFO);
        char *path     = url_part(args.url, &parts, UF_PATH);

        wrkx_configure_fn configure = g_schemas[pd.schema_idx].configure;
        if (configure) {
            wrkx_connect_info ci = {
                .addrinfo = pick_reachable(addr),
                .ssl_ctx  = ssl_ctx,
                .host     = host,
                .password = password,
                .path     = path,
                .url      = args.url,
            };
            configure(&ci);
        }

        free(password);
        free(path);
    } else {
        /* Built-in HTTP/1.1. */
        http1_configure(pick_reachable(addr), ssl_ctx, host);
    }

    /* ------------------------------------------------------------------
     * 8.  Build the scripting engine and configure it (ADR 0002 §3).
     * ---------------------------------------------------------------- */
    script_api    *api = lua_script_api();
    script_engine *eng = api->create(args.script);
    if (eng == NULL) {
        fprintf(stderr, "failed to create scripting engine\n");
        return 1;
    }

    /* Apply helper namespaces registered by active extensions, selecting by
     * engine tag (ADR 0005, Phase 5, t069). A namespace "ns@engine" binds only
     * to the matching engine; the "@engine" suffix is stripped first so the
     * script always sees the bare namespace. The tag rides inside the ns string,
     * so include/wrkx_extension.h is untouched. */
    for (int i = 0; i < g_helper_set_count; i++) {
        char bare[64];
        if (!helper_ns_select(g_helper_sets[i].ns, api->name, bare, sizeof bare))
            continue;
        if (api->register_helpers)
            api->register_helpers(eng, bare,
                                  g_helper_sets[i].helpers,
                                  g_helper_sets[i].count);
    }

    if (api->configure) {
        api->configure(eng, args.url,
                       (const char * const *) args.headers,
                       (size_t) args.n_headers);
    }

    /* init() is now the orchestrator's responsibility (ADR 0005 t070):
     * it runs on the template (thread 0) before static pre-generation, and on
     * each clone after cloning, so every thread gets per-thread init. */

    /* ------------------------------------------------------------------
     * 9.  Run.
     * ---------------------------------------------------------------- */
    char *runtime_msg = format_time_s(args.cfg.duration_us / 1000000ULL);
    printf("Running %s test @ %s\n", runtime_msg, args.url);
    printf("  %"PRIu64" threads and %"PRIu64" connections\n",
           args.cfg.threads, args.cfg.connections);
    free(runtime_msg);

    args.cfg.latency           = args.latency;
    args.cfg.latency_dist_only = args.latency_dist_only;
    args.cfg.u_latency         = args.u_latency;

    /* Use the registered extension protocol, or fall back to HTTP/1.1. */
    protocol *proto = pd.use_ext ? (protocol *) g_schemas[pd.schema_idx].proto
                                 : http1_protocol();
    orchestrator *o = orchestrator_create(args.cfg, proto, api, eng);
    if (o == NULL) {
        fprintf(stderr, "failed to create orchestrator\n");
        return 1;
    }

    rc = orchestrator_run(o);

    orchestrator_destroy(o);

    freeaddrinfo(addr);
    if (ssl_ctx) SSL_CTX_free(ssl_ctx);
    free(schema);
    free(host);
    free(port);

    return rc == 0 ? 0 : 1;
}
