/*
 * src/main.c — wrkx entry point (ADR 0001 Phase 1, P1-5).
 *
 * Wires the three layers together:
 *   1. cli.c  — parse argv → orchestrator_cfg + url + script + headers
 *   2. Protocol detection — schema_table[] maps URL schema → protocol kind,
 *      default port, and TLS flag; no scattered condition chains (t051)
 *   3. <proto>_configure() — resolve target + supply connect info (ADR 0002 §2)
 *   4. api->configure()   — supply URL/headers to Lua engine  (ADR 0002 §3)
 *   5. api->init()        — run wrk.init(); set up default request closure
 *   6. orchestrator_create/run/collect/destroy
 *
 * This is the only file that legitimately includes headers from all three
 * layers (it is the wiring, not a layer).
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <netdb.h>
#include <signal.h>
#include <unistd.h>
#include <sys/socket.h>

#include <openssl/ssl.h>
#include <openssl/err.h>

#include "config.h"
#include "cli.h"
#include "orchestrator.h"
#include "proto/http1.h"
#include "proto/redis.h"
#include "scripting/lua/engine.h"
#include "scripting/lua/redis_helpers.h"
#include "units.h"
#include "http_parser.h"
#include "wrkx_extension.h"

/* Generated by scripts/gen_register_extensions.sh into obj/register_extensions.c.
 * Calls wrkx_extension_init_<name>(api) for each extension active at build time.
 * With no EXTENSIONS, expands to a no-op body. */
extern void wrkx_register_all_extensions(const wrkx_extension_api *api);

/* Extension registration callbacks used at startup.
 * t054: no-op stubs — registry is wired up fully in t055 when Redis moves to
 * the extension system. Extensions can still self-register; nothing breaks. */
static void ext_reg_protocol(const protocol *p) { (void)p; }
static void ext_reg_helpers(const char *ns, const script_helper *h, size_t n)
    { (void)ns; (void)h; (void)n; }

static const wrkx_extension_api g_ext_api = {
    WRKX_EXTENSION_API_VERSION,
    ext_reg_protocol,
    ext_reg_helpers,
};

/* ssl_init() from ssl.c — declared directly to avoid ssl.h → net.h → wrk.h */
extern SSL_CTX *ssl_init(void);

/* -------------------------------------------------------------------------
 * Protocol detection table
 *
 * Maps URL schema strings → (proto_kind, need_tls, default_port).
 * To add a protocol: one table row + one enum value + one case below.
 * ---------------------------------------------------------------------- */

typedef enum { PROTO_HTTP, PROTO_REDIS } proto_kind;

typedef struct {
    proto_kind  kind;
    bool        need_tls;
    const char *default_port;
} proto_info;

typedef struct {
    const char *schema;         /* plain variant:  "http",  "redis"  */
    const char *schema_tls;     /* TLS variant:    "https", "rediss" */
    const char *default_port;
    proto_kind  kind;
} schema_entry;

static const schema_entry schema_table[] = {
    { "http",  "https",  "80",   PROTO_HTTP  },
    { "redis", "rediss", "6379", PROTO_REDIS },
    { NULL,    NULL,     NULL,   PROTO_HTTP  },
};

static proto_info detect_protocol(const char *schema) {
    proto_info info = { PROTO_HTTP, false, "80" };
    if (!schema) return info;
    for (const schema_entry *e = schema_table; e->schema; e++) {
        if (strcmp(schema, e->schema) == 0) {
            info = (proto_info){ e->kind, false, e->default_port };
            return info;
        }
        if (strcmp(schema, e->schema_tls) == 0) {
            info = (proto_info){ e->kind, true, e->default_port };
            return info;
        }
    }
    return info;  /* unknown schema: fall through to HTTP, no TLS */
}

/* -------------------------------------------------------------------------
 * URL decomposition helper (local to wiring)
 * ---------------------------------------------------------------------- */

static char *url_part(const char *url, const struct http_parser_url *p,
                      enum http_parser_url_fields f) {
    if (!(p->field_set & (1 << f))) return NULL;
    uint16_t off = p->field_data[f].off;
    uint16_t len = p->field_data[f].len;
    char *s = calloc(len + 1, 1);
    if (s) memcpy(s, url + off, len);
    return s;
}

/*
 * Pick the first resolved address that actually accepts a connection, mirroring
 * wrk2's wrk.connect() probe. getaddrinfo() with AF_UNSPEC may return an IPv6
 * (::1) address first on a dual-stack host while the server only listens on IPv4
 * (or vice versa); using the head blindly then fails every connect — on Linux
 * `localhost` resolves to ::1 first, so an IPv4-only server is unreachable.
 * Returns a node within `list` (caller still frees the whole list); falls back
 * to the head if none probe-connect.
 */
static struct addrinfo *pick_reachable(struct addrinfo *list) {
    for (struct addrinfo *a = list; a != NULL; a = a->ai_next) {
        int fd = socket(a->ai_family, a->ai_socktype, a->ai_protocol);
        if (fd < 0) continue;
        int ok = (connect(fd, a->ai_addr, a->ai_addrlen) == 0);
        close(fd);
        if (ok) return a;
    }
    return list;
}

/* -------------------------------------------------------------------------
 * main
 * ---------------------------------------------------------------------- */

int main(int argc, char **argv) {
    /* ------------------------------------------------------------------
     * 1.  Parse CLI arguments.
     * ---------------------------------------------------------------- */
    char *header_buf[CLI_MAX_HEADERS];
    cli_args args;
    args.headers = header_buf;

    if (cli_parse_args(argc, argv, &args) != 0) {
        cli_usage(argv[0]);
        return 1;
    }

    /* ------------------------------------------------------------------
     * 2.  Decompose URL and detect protocol.
     * ---------------------------------------------------------------- */
    struct http_parser_url parts;
    memset(&parts, 0, sizeof(parts));
    http_parser_parse_url(args.url, strlen(args.url), 0, &parts);

    char *schema = url_part(args.url, &parts, UF_SCHEMA);
    char *host   = url_part(args.url, &parts, UF_HOST);
    char *port   = url_part(args.url, &parts, UF_PORT);

    proto_info pi = detect_protocol(schema);

    /* Initialize active extensions. Each extension declares its protocol vtable
     * and scripting helpers; the host wires them into the engine below. */
    wrkx_register_all_extensions(&g_ext_api);

    /* Default service port from the table; explicit URL port takes precedence. */
    const char *service = port ? port : pi.default_port;

    /* ------------------------------------------------------------------
     * 3.  TLS setup — driven by the protocol table, not by schema string.
     * ---------------------------------------------------------------- */
    SSL_CTX *ssl_ctx = NULL;
    if (pi.need_tls) {
        ssl_ctx = ssl_init();
        if (ssl_ctx == NULL) {
            fprintf(stderr, "unable to initialise SSL\n");
            ERR_print_errors_fp(stderr);
            return 1;
        }
    }

    /* ------------------------------------------------------------------
     * 4.  Resolve host:service → addrinfo.
     * ---------------------------------------------------------------- */
    struct addrinfo hints, *addr = NULL;
    memset(&hints, 0, sizeof(hints));
    hints.ai_family   = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;

    int rc = getaddrinfo(host, service, &hints, &addr);
    if (rc != 0) {
        fprintf(stderr, "unable to resolve %s:%s — %s\n",
                host ? host : "(null)", service ? service : "(null)",
                gai_strerror(rc));
        return 1;
    }

    /* ------------------------------------------------------------------
     * 5.  Configure the Protocol Engine (ADR 0002 Decision 2).
     *     One case per protocol kind; all schema knowledge is in the table.
     * ---------------------------------------------------------------- */
    signal(SIGPIPE, SIG_IGN);

    switch (pi.kind) {
        case PROTO_REDIS: {
            /* redis://[password@]host[:port][/db]
             * UF_USERINFO holds the password (no username in Redis auth).
             * UF_PATH holds the db index as "/N" (default 0). */
            char *password = url_part(args.url, &parts, UF_USERINFO);
            char *path     = url_part(args.url, &parts, UF_PATH);
            int   db       = (path && path[0] == '/' && path[1] != '\0')
                             ? atoi(path + 1) : 0;
            redis_configure(pick_reachable(addr), ssl_ctx, host, password, db);
            free(password);
            free(path);
            break;
        }
        default:
            http1_configure(pick_reachable(addr), ssl_ctx, host);
            break;
    }

    /* ------------------------------------------------------------------
     * 6.  Build the scripting engine and configure it (ADR 0002 §3).
     * ---------------------------------------------------------------- */
    script_api    *api = lua_script_api();
    script_engine *eng = api->create(args.script);
    if (eng == NULL) {
        fprintf(stderr, "failed to create scripting engine\n");
        return 1;
    }

    /* Register protocol-specific Lua helpers before api->init() so the
     * user's init() hook can call e.g. redis.command() during setup. */
    if (pi.kind == PROTO_REDIS)
        lua_register_redis_helpers(eng);

    if (api->configure) {
        api->configure(eng, args.url,
                       (const char * const *) args.headers, (size_t) args.n_headers);
    }

    /* init sets up wrk.request closure and calls setup()/init() hooks */
    api->init(eng, 0, args.cfg.connections);

    /* ------------------------------------------------------------------
     * 7.  Run.
     * ---------------------------------------------------------------- */
    char *runtime_msg = format_time_s(args.cfg.duration_us / 1000000ULL);
    printf("Running %s test @ %s\n", runtime_msg, args.url);
    printf("  %"PRIu64" threads and %"PRIu64" connections\n",
           args.cfg.threads, args.cfg.connections);
    free(runtime_msg);

    args.cfg.latency           = args.latency;
    args.cfg.latency_dist_only = args.latency_dist_only;
    args.cfg.u_latency         = args.u_latency;

    protocol *proto = (pi.kind == PROTO_REDIS) ? redis_protocol()
                                                : http1_protocol();
    orchestrator *o = orchestrator_create(args.cfg, proto, api, eng);
    if (o == NULL) {
        fprintf(stderr, "failed to create orchestrator\n");
        return 1;
    }

    rc = orchestrator_run(o);

    orchestrator_destroy(o);

    /* Cleanup */
    freeaddrinfo(addr);
    if (ssl_ctx) SSL_CTX_free(ssl_ctx);
    free(schema);
    free(host);
    free(port);

    return rc == 0 ? 0 : 1;
}
