EXT_SRCS     += extensions/memcached/mc_codec.c \
                extensions/memcached/mc_request.c \
                extensions/memcached/memcached.c \
                extensions/memcached/init.c
EXT_INIT_FNS += wrkx_extension_init_memcached
EXT_CFLAGS   += -Iextensions/memcached

